INSERT INTO users (name, email, password) VALUES ('Alice', 'alice@gmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Kira', 'kira@gmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Colin', 'colin@gmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Matt', 'matt@gmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Alex', 'alex@gmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Dylan', 'dylan@gmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Kim kardashian', 'kim123@gmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Kyle', 'kyle@gmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Katherine', 'katherine321@gmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Michael M', 'kira123@gmail.com', 'password');